#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace ABP_Katana { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_GhostPainting { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_EMF_Arms { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_OuijaBoard { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonTape { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Ailen { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ESG_Arms { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_BaseEntity { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonElderScroll { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Tape_0 { class ABP_Tape_C; }

namespace ABP_Thermometer { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Pet_Dog { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonESG { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonOuijiaBoard { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Pet_Flamingo { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonEasel { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonSaltGun { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Pet_Chicken { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonCross { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonBlacksmithHammer { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Pet_Turtle { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonCamera { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_TarotCards { struct FAnimBlueprintGeneratedConstantData; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace ABP_ThirdPersonFulu { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonSpiritBox { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonSanityPill { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPerson_Necromicon { struct FAnimBlueprintGeneratedConstantData; }

namespace CC_Post_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_BlacksmithHammer { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ElderScroll { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Tape_Arms { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Cross { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_BaseInteraction_0 { class ABP_BaseInteraction_C; }

namespace ABP_UvLight_Tool { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Finger { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonUVLight { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Patient { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonSaltBarrier { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Glass_Arms { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_EvilDemon { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_UvLight { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Flashlight_Arms { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_SaltBarrier { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_LightSwitch_0 { class ABP_LightSwitch_C; }

namespace ABP_Camera { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_SaltGun { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_LightSwitch { class ABP_LightSwitch_C; }

namespace ABP_Rat_Arms { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonKatana { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonThermoManuel { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonPocketWatch { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonFinger { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Necromicon_Arms { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Candle { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Necromicon { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_BaseInteraction { class ABP_BaseInteraction_C; }

namespace ABP_SwampWatcher { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_BaseTool { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonEmpty { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonRat { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonEMF { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonCandle { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonVoodooDoll { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonTarotCard { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonGlass { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonFlashlight { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_ThirdPersonTripodeCamera { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_VoodooBaby { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Zombie { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_FaceMonster { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_BabyDemon { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_FatDemon { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Banshee { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Cat_Pet { struct FAnimBlueprintGeneratedConstantData; }

namespace BP_Tape { class ABP_Tape_C; }

namespace ABP_TripodeCamera { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_PocketWatch_Arms { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_SpiritBox { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_VoodooDoll_Arms { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Fulu { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Empty_Arm { struct FAnimBlueprintGeneratedConstantData; }


namespace CC_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_SanityPills_0
{
	class UABP_SanityPills_C;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_ToolLayerArms
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Mannequin_ControlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace ABP_CockRoach
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Base_Arms
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_PocketWatch
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_SanityPills
{
	class UABP_SanityPills_C;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace CR_Foot_IK
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace CR_Speed_Warping
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace ABP_ThirdPersonToolLayer
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace CR_Hand_IK
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace ABP_DynamicGhost
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_ThirdPersonCharacter
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_TarotCard
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
